// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZlp5_oEf8d4YuOa4hUiBnL_JQWlxpZs',
    appId: '1:328292031774:web:08293d86bb2a7de7df3d0f',
    messagingSenderId: '328292031774',
    projectId: 'cmsc23-slambook-app-bsy',
    authDomain: 'cmsc23-slambook-app-bsy.firebaseapp.com',
    storageBucket: 'cmsc23-slambook-app-bsy.appspot.com',
    measurementId: 'G-YGV185QYPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGgIisDyNbA-dRYW5ZMjvjtsZYpVcXFI',
    appId: '1:328292031774:android:9d051d8a33117f7cdf3d0f',
    messagingSenderId: '328292031774',
    projectId: 'cmsc23-slambook-app-bsy',
    storageBucket: 'cmsc23-slambook-app-bsy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FOyCz9gEk2-you2e6YBK_nlnDC2FPBE',
    appId: '1:328292031774:ios:1ead31d4a7fe1b8bdf3d0f',
    messagingSenderId: '328292031774',
    projectId: 'cmsc23-slambook-app-bsy',
    storageBucket: 'cmsc23-slambook-app-bsy.appspot.com',
    iosClientId: '328292031774-halaa1p74tlk1bskbktpnlg03sl5qh3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.syExercise08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0FOyCz9gEk2-you2e6YBK_nlnDC2FPBE',
    appId: '1:328292031774:ios:1ead31d4a7fe1b8bdf3d0f',
    messagingSenderId: '328292031774',
    projectId: 'cmsc23-slambook-app-bsy',
    storageBucket: 'cmsc23-slambook-app-bsy.appspot.com',
    iosClientId: '328292031774-halaa1p74tlk1bskbktpnlg03sl5qh3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.syExercise08',
  );
}
